  mongoKlov:
    image: mongo
    restart: always
    hostname: mongodb
    command: mongod --port 8082
    ports:
      - 8082:8082

  klov:
    image: shinyay/docker-mvn-jdk8:3.5.0
    ports:
    - "1337:1337"
    volumes:
    - ".:/usr/src/myapp"
    working_dir: /usr/src/myapp
    command: >
        bash -c "java -jar klov-0.2.5.jar"
    links:
    - mongoKlov
    
